"""Smoke tests for the demo's streamlit-free logic layer.

These require the synthetic samples to exist; they are generated by
``python -m eval.generate_synthetic_forms`` (also done in CI before tests there,
and present in the repo). If absent, the sample-dependent tests are skipped.
"""

from __future__ import annotations

import pytest
from app import demo_core


def test_split_fields_separates_checkboxes():
    from formextract.config import CHECKBOX_FIELDS

    fields = {
        "Site_Address": "1 Main St",
        "Method_of_Alarm_Activation": ["Pull Station"],
        "Evacuation_Type": "Full Evacuation to Outside",
    }
    checkbox, other = demo_core.split_fields(fields)
    assert set(checkbox).issubset(CHECKBOX_FIELDS)
    assert "Method_of_Alarm_Activation" in checkbox
    assert "Site_Address" in other


@pytest.mark.skipif(not demo_core.LABELS_PATH.exists(), reason="synthetic samples not generated")
def test_load_samples_matches_pdfs():
    samples = demo_core.load_samples()
    assert samples, "expected at least one synthetic sample"
    for s in samples[:3]:
        assert s.pdf_path.exists(), f"missing pdf for {s.source_file}"
        assert isinstance(s.fields, dict) and s.fields


@pytest.mark.skipif(not demo_core.LABELS_PATH.exists(), reason="synthetic samples not generated")
def test_render_pdf_pages_returns_two_pages():
    sample = demo_core.load_samples()[0]
    pages = demo_core.render_pdf_pages(sample.pdf_path)
    assert len(pages) == 2
    assert all(p[:8] == b"\x89PNG\r\n\x1a\n" for p in pages)  # PNG magic bytes
